language: node_js
node_js:
  - "4.2"
  - "5.5"

before_script:
  - npm install -g codacy-coverage
  - npm install -g coveralls
  - npm install -g mocha-lcov-reporter

script:
  - npm run test-cov -- -- --reporter mocha-lcov-reporter

after_script:
  - cat ./coverage/lcov.info | codacy-coverage
  - cat ./coverage/lcov.info | coveralls
